import localFont from "next/font/local";
import Header from "@/app/components/Header"; // Ensure correct casing
import Footer from "@/app/components/Footer"; // Ensure correct casing
import "./globals.css"; // Global styles

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Root layout component
export const metadata = {
  title: "TODO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header /> {/* Render Header */}
        {children} {/* Render page content */}
        <Footer /> {/* Render Footer */}
      </body>
    </html>
  );
}